# Generated by Django 2.2.5 on 2019-09-17 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='hora_compra',
            new_name='fecha_envio',
        ),
    ]
